services:
  - type: web
    name: interview-pro-ai-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: GROQ_TRANSCRIBE_MODEL
        value: whisper-large-v3
      - key: GROQ_VISION_MODEL
        value: llama-3.2-11b-vision-preview
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
